Pages Design and redirections
agtugchik/project-management-app pull request #6
Opened 2022-11-29 15:43 UTC by atcherdsd

2022-11-29 16:19 UTC, mazeltovik approved these changes

2022-12-04 15:01 UTC, KrohNic requested changes

2022-12-04 15:13 UTC, agtugchik approved these changes

2022-12-04 17:52 UTC, atcherdsd commented on src/components/UI/Navbar/Navbar.tsx
> +  const [isLoadingLocal, setIsLoadingLocal] = useState(true);
К размещенному выше комментарию касательно строки 26 этого же файла - пробовал убрать этот стейт, но тогда в хедере происходит видимый визуально сначала рендер списка публичных роутов, а затем - приватных. С этим же кодом в хедер рендерится сразу нужный список.
Предлагаю этот код оставить.

2022-12-04 19:42 UTC, atcherdsd commented on src/components/App/App.tsx
> +        navigate(Paths.MainPage);
Перенес логику в роутер. Саму логику не изменял, т.к. целью данного кода ставил выполнение перехода на Main Page именно в случае ввода в адресную строку запроса, содержащего signin или signup.

2022-12-04 19:48 UTC, atcherdsd commented on src/components/Modal/modals/createNewBoardModal.tsx
> +    return setInvitedUsers([]);
Убрал лишний код

2022-12-04 19:52 UTC, atcherdsd commented on src/components/createNewBoardForm/createNewBoardForm.tsx
> +  }, [setAutoCompContent]);
Убрал эти строчки кода, которые оказались лишними

2022-12-04 20:44 UTC, atcherdsd commented on src/components/Modal/modals/createNewBoardModal.tsx
> +    if (value && (value == 'Cancel' || value == 'Отмена')) {
Пересмотрел этот блок кода и использование данной функции - применяется только для обработки клика по кнопке Cancel - и решил пойти другим путем и упростить код в данном случае: повесил обработчик непосредственно на кнопку и убрал лишние поиск элемента и условие в теле функции.

2022-12-05 07:13 UTC, KrohNic approved these changes

2022-12-05 07:13 UTC, merged